第5回の課題提出
Yamazaki-21/RaiseTech pull request #6
Opened 2024-12-27 08:46 UTC by Yamazaki-21

第5回の課題を実施いたしました。
ご確認をお願いいたします。

2024-12-28 09:37 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-12-28 09:37 UTC, MasatoshiMizumoto commented on lecture05/lecture05.md
> +- 画像がS3に保存されるように設定した後、webブラウザで画像を登録
アップロードした画像がTOP画面の時点で見られるのが正しいです！
対応いただきたいです！

2024-12-30 07:04 UTC, Yamazaki-21 commented on lecture05/lecture05.md
> +- 画像がS3に保存されるように設定した後、webブラウザで画像を登録
vipsをインストールして、アップロードした画像をTOP画面の時点で見られるようにしました。
ご確認をお願いいたします。

2024-12-30 08:05 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-12-30 08:10 UTC, merged